name: Load Test

on:
  workflow_call:

jobs:

  LoadTest:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CHAVEDEACESSO }}
          aws-secret-access-key: ${{ secrets.CHAVEDEACESSOSSECRETA }}
          aws-region: us-east-2
          
      - name: clone do repositório
        run: git clone https://github.com/vitorgrisolia/Infra_CI.git
      
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
        
      - name: criar a infra do terraform
        run: terraform -chdir=Infra_CI/env/Homolog init
      
      - name: comando de encerrar
        run: terraform -chdir=Infra_CI/env/Homolog destroy -auto-approve

      - name: Executar a infra do terraform
        run: terraform -chdir=Infra_CI/env/Homolog apply -auto-approve

      - name: saida do terraform
        run: echo "$(terraform -chdir=Infra_CI/env/Homolog output -raw IP_alb)"
        id: URL

      - name: Setup Python
        uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.10"
          
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            locust

      - run: | 
          echo "from locust import HttpUser, TaskSet, task, between" >> locustfile.py
          echo "" >> locustfile.py
          echo "class UserTasks(TaskSet):" >> locustfile.py
          echo "	@task(1)" >> locustfile.py
          echo "	def index(self):" >> locustfile.py
          echo '		self.client.get("/vitor")' >> locustfile.py
          echo "" >> locustfile.py
          echo "class WebsiteUser(HttpUser):" >> locustfile.py
          echo "	tasks = [UserTasks]" >> locustfile.py
          echo "	wait_time = between(1, 5)" >> locustfile.py

      - name: Play Test de carga
            # locust -f $file --headless -u $INPUT_USERS -r $INPUT_RATE --run-time $INPUT_RUNTIME -H $INPUT_URL
        run: sleep 60s; locust -f locustfile.py --headless -u 10 -r 5 --run-time 60s -H http://${{ steps.URL.outputs.stdout }}

      - name: comando de encerrar geral
        run: terraform -chdir=Infra_CI/env/Homolog destroy -auto-approve
